# Generated by Django 3.0.5 on 2020-04-07 01:33

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200407_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
